name: Flowzone

on:
  # Meant to deploy docs to Cloudflare Pages once each day
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master
    secrets: inherit
    with:
      cloudflare_website: "balenacloud-docs"
      docusaurus_website: false
